### ISSUE TITLE
Issues with image uploads

### ISSUE THREAD

**Issue by Geo-GPSGaming** [icon-community/CPS#29]
The image appears to upload properly and gets a green check mark and then sometimes changes into an error box with the following error in dev console: GET https://gateway.ipfs.io/ipfs/bafybeif2ymoo6onqqb4upyr5tvdjbkwivwz27f5ms2dre5pb3p62ropo7m 429

**Comment by tjhunt1** [comment]
This is an issue w/ IPFS API itself - should only happen rarely but @Geo-GPSGaming please let us know if you get this issue again in the future & we'll explore a dynamic URL for the images
