### ISSUE TITLE
Wiki: Reorganize Table of Contents

### ISSUE THREAD

**Issue by han-so1omon** [icon-community/CPS#31]
@tjhunt1 I think it would be nice if the [Introduction](https://github.com/icon-community/CPS/wiki/Introduction) page were at the top of the sidebar as well as the Table of Contents.

[This page](https://docs.github.com/en/communities/documenting-your-project-with-wikis/creating-a-footer-or-sidebar-for-your-wiki) on creating a custom sidebar may be helpful to figure out how to accomplish this

Thoughts?

**Comment by tjhunt1** [comment]
@han-so1omon - custom sidebar created. Let me know if you would like to see a different order

**Comment by han-so1omon** [comment]
@tjhunt1 Looks great!
