### ISSUE TITLE
ICON Web Studio link on Landing Page doesn't work

### ISSUE THREAD

**Issue by theconnectooor** [icon-community/CPS#34]
https://iconweb.studio/

<img width="296" alt="Screen Shot 2022-08-09 at 3 01 22 PM" src="https://user-images.githubusercontent.com/98855020/183750105-c39ed2b2-0b73-40b2-8453-7b7e3549761b.png">

**Comment by tjhunt1** [comment]
Also get this for opendevicon link on landing page 

<img width="330" alt="Screen Shot 2022-08-09 at 3 01 57 PM" src="https://user-images.githubusercontent.com/98855020/183750206-f8d82666-fcd4-401a-93cb-9c46ac700deb.png">
