### ISSUE TITLE
Period Change Email Notification

### ISSUE THREAD

**Issue by theconnectooor** [icon-community/CPS#4]
### Two Issues:

1) Period change notification was emailed 6 times, each 30min apart.

2) "ICX_Station" P-Rep was renamed to "Lydia Labs" P-Rep, so notification system isn't properly pulling this updated data.

![image](https://user-images.githubusercontent.com/98855020/178853592-5333fb0b-c6b8-42c1-8628-cfdc55c7c834.png)

**Comment by sdpisreddevil** [comment]
1. Cron update wallet balance was not enough to call the txns, which triggers the emails. 

2. Will look over for that.
