### ISSUE TITLE
pre-filling proposal/progress report templates

### ISSUE THREAD

**Issue by theconnectooor** [icon-community/CPS#55]
proposal template and progress report template pre-filled as part of the CPS UI instead of a blank slate

[https://github.com/icon-project/grants-program/tree/main/templates](https://github.com/icon-project/grants-program/tree/main/templates )

**Comment by han-so1omon** [comment]
@theconnectooor is this completed?

**Comment by theconnectooor** [comment]
completed - however instead of prefilling a singular text box we should look into having multiple sections for each part of the progress report to be filled in so that "required" sections can't be deleted and the proposal contents become more standardized

**Comment by han-so1omon** [comment]
Ok, that should be a separate issue, then
