### ISSUE TITLE
Hide notification button when empty

### ISSUE THREAD

**Issue by theconnectooor** [icon-community/CPS#60]
When the Validators have performed all voting and have "0" notifications left - the red notification button should disappear.
<img width="270" alt="Screen Shot 2022-10-05 at 10 18 30 AM" src="https://user-images.githubusercontent.com/98855020/194097998-795a316b-4ea2-4070-b872-93bbcce61896.png">

**Comment by han-so1omon** [comment]
@theconnectooor is this completed?

**Comment by theconnectooor** [comment]
no I don't believe so
