### ISSUE TITLE
Voting results not loading on Rejected Proposals in "Proposal History"

### ISSUE THREAD

**Issue by theconnectooor** [icon-community/CPS#62]
[https://cps.icon.community/proposals/bafybeib2i53vwxv3fprhdansejqa2tprep5aly4yikhkfy4xqtnekyktra](https://cps.icon.community/proposals/bafybeib2i53vwxv3fprhdansejqa2tprep5aly4yikhkfy4xqtnekyktra )

**Comment by theconnectooor** [comment]
@sdpisreddevil are we supposed to be able to see the voting results in the link above?

They still don't show but I think they probably should

**Comment by sdpisreddevil** [comment]
This was Sponsor Rejected proposal which won't be having any comments.

**Comment by theconnectooor** [comment]
Interesting - I didn't know sponsor rejected proposals were public
